branches:
  only:
    - master

environment:
  PATH: C:\Ruby%RUBY_VERSION%\DevKit\mingw\bin;C:\Ruby%RUBY_VERSION%\bin;C:\Ruby%RUBY_VERSION%\DevKit\bin;%PATH%
  matrix:
  - LANG: "ruby"
    RUBY_VERSION: "24-x64"
  - LANG: "ruby"
    RUBY_VERSION: "22"

build: off

test_script:
  - cd %LANG%
  - call ci.bat
