[package]
name        = "sivchain"
description = "Advanced symmetric encryption using the AES-SIV (RFC 5297) and CHAIN constructions"
version     = "0.0.0"
license     = "MIT"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
homepage    = "https://sivchain.org"
repository  = "https://github.com/zcred/sivchain/tree/master/rust"
readme      = "README.md"
categories  = ["cryptography"]
keywords    = ["cryptography", "encryption", "security", "streaming"]

[dependencies]
